volumes:
  pgdata:
  web-root:

services:
  web:
    image: trompa-align-${CLARA_ENV}
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    platform: linux/amd64
    env_file: production-environment
    restart: always
    expose:
      - "8000"
    command:
      - gunicorn
      - -b
      - 0.0.0.0:8000
      - -w
      - 2
      - -t
      - 5
      - app:app
    volumes:
      - "${CLARA_BUILD_DIRECTORY}:/clara"
      - web-root:/web-root

  redis:
    image: "redis:alpine"

  celery:
    image: trompa-align-${CLARA_ENV}
    restart: always
    env_file: celery-environment
    command:
      - celery
      - -A
      - trompaalign.celery
      - worker

  celery-beat:
    image: trompa-align-${CLARA_ENV}
    restart: always
    env_file: celery-environment
    command:
      - celery
      - -A
      - trompaalign.celery
      - beat

  db:
    image: postgres:18
    restart: always
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_DB: solid_oidc
    volumes:
      - pgdata:/var/lib/postgresql
