name: Ruff Format
on:
  pull_request:
    branches: [ '*' ]
    types: [ opened, synchronize, reopened, ready_for_review ]
jobs:
  ruff-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: astral-sh/ruff-action@v4.1.0
        with:
          version-file: "uv.lock"
          args: "--version"
      - run: ruff check
      - run: ruff format --check --diff
